### ISSUE TITLE
Is there a way to add a node with SNMP v2c credentials

### ISSUE THREAD

**Issue by smatterchew** [ashleyghooper/solarwinds_ansible#6]
We have a couple hundred systems here that don't support SNMP v3 (Windows of course), and the security team does not allow a polling account for WMI to be in the local administrators group.  To date, the Orion team adds all Windows devices by hand with SNMP v2c. 

Thank you.

**Comment by ashleyghooper** [comment]
Hi again!
Yes this should work by use of the `credential_names` argument to the `orion_node` module. The pre-requisite is that any SNMP community strings to be used for discovery/polling need to be already defined in your SolarWinds instance as shared credentials (`SolarWinds.Orion.Core.Models.Credentials.SnmpCredentialsV2`). There is no specific credential type for SNMPv1, but I would expect the v2 credential to work.

Incidentally, for SNMPv2 credentials, the way SolarWinds stores them, the credential name seems to simply be the community string itself, however it still _does_ have to have been set up as a shared SNMPv2 credential in advance.

In case it helps, here's an example of a SWIS query to look up all SNMPv2 credentials.

```
SELECT ID, Name, Description, CredentialType, CredentialOwner FROM Orion.Credential WHERE CredentialType = 'SolarWinds.Orion.Core.Models.Credentials.SnmpCredentialsV2'
```
