### ISSUE TITLE
solarwinds_info module return value format

### ISSUE THREAD

**Issue by ashleyghooper** [ashleyghooper/solarwinds_ansible#7]
From your example I get:

```json
    "msg": {
        "changed": false,
        "failed": false,
        "info": {
            "count": 1,
            "data": [
                {
                    "AvgCPUUtil": 0.0,
                    "BusinessLayerPort": 17777,
```
Modules from Red Hat and other projects seem to have a standard return format that looks more like this one from the [Project List API endpoint in Ansible Tower](https://docs.ansible.com/ansible-tower/2.3.0/html/towerapi/projects.html):
```json
{
    "count": 99,
    "next": null,
    "previous": null,
    "results": [
        ...
    ]
}
```
Would it be possible to have these modules follow this example for returned data structures?
```json
{
    "changed": false,
    "count": 7
    "failed": false,
    "results": [
        {
            "AvgCPUUtil": 0.0,
            "BusinessLayerPort": 17777,
```
Thank you

_Originally posted by @smatterchew in https://github.com/ashleyghooper/solarwinds_ansible/issues/5#issuecomment-1376050311_

**Comment by ashleyghooper** [comment]
I've tabulated below the majority of the `*_info` modules in the `community.general` collection, along with their return values.

There is a lot of variation between modules, but if there's any naming that is most prevalent I think it would be to return an object named for the module name itself, or some derivation of the name.

| Module | Module-specific return value(s) |
| --- | --- |
| [ali_instance_info](https://docs.ansible.com/ansible/latest/collections/community/general/ali_instance_info_module.html#return-values) | `ids`, `instances` |
| [dnsimple_info](https://docs.ansible.com/ansible/latest/collections/community/general/dnsimple_info_module.html#return-values) | `dnsimple_domain_info`, `dnsimple_record_info`, and `dnsimple_records_info` |
| [gconftool2_info](https://docs.ansible.com/ansible/latest/collections/community/general/gconftool2_info_module.html#return-values) | `value` |
| [github_webhook_info](https://docs.ansible.com/ansible/latest/collections/community/general/github_webhook_info_module.html#return-values) | `hooks` |
| [hpilo_info](https://docs.ansible.com/ansible/latest/collections/community/general/hpilo_info_module.html#return-values) | dict containing properties for a single item, e.g. `host_power_status`, `hw_bios_date`, etc |
| [idrac_redfish_info](https://docs.ansible.com/ansible/latest/collections/community/general/idrac_redfish_info_module.html#return-values) | `msg` |
| [ilo_redfish_info](https://docs.ansible.com/ansible/latest/collections/community/general/ilo_redfish_info_module.html#return-values) | `ilo_redfish_info` |
| [jenkins_job_info](https://docs.ansible.com/ansible/latest/collections/community/general/jenkins_job_info_module.html#return-values) | `jobs` |
| [keycloak_clientsecret_info](https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_clientsecret_info_module.html#return-values) | `clientsecret_info`, `msg` |
| [keycloak_realm_info](https://docs.ansible.com/ansible/latest/collections/community/general/keycloak_realm_info_module.html#return-values) | `msg`, `realm_info` |
| [keyring_info](https://docs.ansible.com/ansible/latest/collections/community/general/keyring_info_module.html#return-values) | `passphrase` |
| [manageiq_policies_info](https://docs.ansible.com/ansible/latest/collections/community/general/manageiq_policies_info_module.html#return-values) | `profiles` |
| [manageiq_tags_info](https://docs.ansible.com/ansible/latest/collections/community/general/manageiq_tags_info_module.html#return-values) | `tags` |
| [memset_memstore_info](https://docs.ansible.com/ansible/latest/collections/community/general/memset_memstore_info_module.html#return-values) | `memset_api` |
| [memset_server_info](https://docs.ansible.com/ansible/latest/collections/community/general/memset_server_info_module.html#return-values) | `memset_api` |
| [nginx_status_info](https://docs.ansible.com/ansible/latest/collections/community/general/nginx_status_info_module.html#return-values) | dict containing properties for a single item, e.g. `active_connections`, `data`, `requests`, etc |
| [nomad_job_info](https://docs.ansible.com/ansible/latest/collections/community/general/nomad_job_info_module.html#return-values) | `result` |
| [one_image_info](https://docs.ansible.com/ansible/latest/collections/community/general/one_image_info_module.html#return-values) | `images` |
| [oneview_datacenter_info](https://docs.ansible.com/ansible/latest/collections/community/general/oneview_datacenter_info_module.html#return-values) | `datacenter_visual_content`, `datacenters` |
| [oneview_enclosure_info](https://docs.ansible.com/ansible/latest/collections/community/general/oneview_enclosure_info_module.html#return-values) | `enclosure_environmental_configuration`, `enclosure_script`, `enclosure_utilization`, `enclosures` |
| [online_server_info](https://docs.ansible.com/ansible/latest/collections/community/general/online_server_info_module.html#return-values) | `online_server_info` |
| [onepassword_info](https://docs.ansible.com/ansible/latest/collections/community/general/onepassword_info_module.html#return-values) | `onepassword` |
| [pip_package_info](https://docs.ansible.com/ansible/latest/collections/community/general/pip_package_info_module.html#return-values) | `packages` |
| [pipx_info](https://docs.ansible.com/ansible/latest/collections/community/general/pipx_info_module.html#return-values) | `application` |
| [proxmox_domain_info](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_domain_info_module.html#return-values) | `proxmox_domains` |
| [proxmox_group_info](https://docs.ansible.com/ansible/latest/collections/community/general/proxmox_group_info_module.html#return-values) | `proxmox_groups` |
| [redis_info](https://docs.ansible.com/ansible/latest/collections/community/general/redis_info_module.html#return-values) | `info` |
| [rundeck_job_executions_info](https://docs.ansible.com/ansible/latest/collections/community/general/rundeck_job_executions_info_module.html#return-values) | `executions` |
| [scaleway_server_info](https://docs.ansible.com/ansible/latest/collections/community/general/scaleway_server_info_module.html#return-values) | `scaleway_server_info` |

**Comment by ashleyghooper** [comment]
The module [rundeck_job_executions_info](https://github.com/ansible-collections/community.general/blob/main/plugins/modules/rundeck_job_executions_info.py) includes some pagination logic.

Aside from that one, it doesn't appear that any of the other modules have pagination logic or even return a `count` either.

**Comment by smatterchew** [comment]
> Aside from that one, it doesn't appear that any of the other modules have pagination logic or even return a `count` either.

Yes.  I looked at the Synopsis of each of the modules above and I'm not sure many of them would need pagination.  For the `solarwinds_info` module, maybe it's best to leave pagination out until there is more interest in it.  It would be a shame to implement pagination and nobody needs it.

As far as the `solarwinds_info` return data structure, I do think the example from the Project List endpoint above is relevant.  The module is sending a SQL (related) query and I am getting results back.

**Comment by ashleyghooper** [comment]
I was just reviewing the common return values for Ansible modules and was reminded why I had earlier switched from returning `results`.

> [results](https://docs.ansible.com/ansible/latest/reference_appendices/common_return_values.html#results)
> If this key exists, it indicates that *a loop was present for the task and that it contains a list of the normal module ‘result’ per item*.

In light of that, naming the key `results` would be incorrect/misleading usage.

**Comment by ashleyghooper** [comment]
Return format is as below. I'm going to go ahead and merge the branch containing `solarwinds_info`.

```json
{
    "changed": false,
    "count": 1,
    "failed": false,
    "solarwinds_info": [
        {
            "AvgCPUUtil": 0.0,
            "BusinessLayerPort": 17777,
            "CompanyName": "",
            "CustomerID": null,
            "Description": null,
        }
    ]
}
```
